// <auto-generated/>

global using global::Microsoft.EntityFrameworkCore;
global using global::Microsoft.EntityFrameworkCore.Metadata.Builders;
global using global::Microsoft.Extensions.DependencyInjection;
global using global::Microsoft.Extensions.Logging;
global using global::System;
global using global::System.Collections.Generic;
global using global::System.Linq;
global using global::System.Linq.Expressions;
global using global::Temple.Core.Constants;
global using global::Temple.Core.Enumerations;
global using global::Temple.Core.Models.Entities.Audits;
global using global::Temple.Core.Models.Entities.ReceiptBooks;
global using global::Temple.Core.Models.Entities.Users;
global using global::Temple.Core.Models.Errors;
global using global::Temple.SqlServer.Extensions;
