// <auto-generated/>
global using global::Microsoft.AspNetCore.Hosting;
global using global::Microsoft.AspNetCore.Http;
global using global::Microsoft.Extensions.DependencyInjection;
global using global::Microsoft.Extensions.Logging;
global using global::System;
global using global::System.Collections.Generic;
global using global::System.Linq;
global using global::System.Linq.Expressions;
global using global::System.Security.Claims;
global using global::Temple.Core.Enumerations;
global using global::Temple.Core.Extensions;
global using global::Temple.Core.Models.Entities.Audits;
global using global::Temple.Core.Models.Entities.ReceiptBooks;
global using global::Temple.Core.Models.Entities.Users;
global using global::Temple.Core.Models.Errors;
